"use client";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min";
import { store } from "@/store/store";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from '../components/Header/index'





export const metadata = {
  title: "TMDB Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Provider store={store}>
          <Header />
          {children}
          <ToastContainer />
        </Provider>
      </body>
    </html>
  );
}
